version: '3'
services:
  db:
    image: 'postgres:14-alpine'
    platform: linux/amd64
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
    networks:
      book_share-net:

  redis:
    image: 'redis:6-alpine'
    ports:
      - '6379:6379'
    networks:
      book_share-net:

  web:
    build: .
    platform: linux/arm64/v8
    volumes:
      - .:/book_share/
      - bundle-data:/usr/local/bundle
    ports:
      - '5000:5000'
    depends_on:
      - db
    command: /bin/sh -c "bundle && exec rails s -p 5000 -b '0.0.0.0'"

    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: 'development'
    networks:
      book_share-net:

networks:
  book_share-net:

volumes:
  bundle-data:
